version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1o5psq12gup9w"
s3_prefix = "sam-app-2"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
