AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3


Resources:
  # libs:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: layer-pandas-3
  #     Description: Dependencies for the blank sample app.
  #     # ContentUri: 's3://test-media-incloud-2/my-layer.zip'
  #     # LayerContent:
  #     #   S3Bucket: test-media-incloud-2
  #     #   S3Key: _layers/layer.zip
  #     #   Version: 1
  #     ContentUri: _layers
  #     CompatibleRuntimes:
  #       - python3.8
  #       - python3.9  

  QueryDynamo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: query_dynamo
      Handler: hello_efs.scan_dynamo.lambda_handler
      Runtime: python3.8
      Timeout: 75
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess
      Events:
        HelloWorld:
          Type: Api
          Properties:
            # Auth: null
            Path: /query
            Method: get

  CreateDynamo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create_dynamo
      Handler: hello_efs.create_dynamo.lambda_handler
      Runtime: python3.8
      Timeout: 75
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess
      # Layers:
      #   - !Ref libs
      Events:
        HelloWorld:
          Type: Api
          Properties:
            # Auth: null
            Path: /create
            Method: post

  UploadMedia:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: upload_media
      Handler: hello_efs.upload_media.lambda_handler
      Runtime: python3.8
      Timeout: 75
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess
      Events:
        UploadS3Gateway:
          Type: Api
          Properties:
            # Auth: null
            Path: /upload_media
            Method: post




Outputs:
  HelloEfsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello EFS function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
