AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  QueryDynamo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: query_dynamo
      Handler: hello_efs.scan_dynamo.lambda_handler
      Runtime: python3.8
      Timeout: 75
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess
      Events:
        HelloWorld:
          Type: Api
          Properties:
            # Auth: null
            Path: /query
            Method: get

  CreateDynamo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create_dynamo
      Handler: hello_efs.create_dynamo.lambda_handler
      Runtime: python3.8
      Timeout: 75
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess
      Events:
        HelloWorld:
          Type: Api
          Properties:
            # Auth: null
            Path: /create
            Method: post
Outputs:
  HelloEfsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello EFS function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
